import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import alias from '@rollup/plugin-alias';
import copy from 'rollup-plugin-copy';

const isProd = process.env.BUILD === 'production';

/**
 * Where each build leaves a folder that can be dropped into a vault.
 *
 * The directory name has to match the plugin id in manifest.json, because
 * Obsidian identifies an installed plugin by its folder name.
 */
const LOADABLE_PLUGIN_DIR = './build/glyphit';

/**
 * Path of the vault plugin directory to copy the build into, if one is set up.
 *
 * `env.js` is deliberately untracked, since it points at whatever vault the
 * developer happens to test in. It is optional: without it the build still
 * produces `main.js` in the project, it just is not copied anywhere. Requiring
 * it meant a fresh clone could not build at all, which is also why there is no
 * CI job building the plugin.
 *
 * To have the build install itself into a vault, create `env.js` with:
 *
 * ```js
 * export const obsidianExportPath =
 *   '<path-to-vault>/.obsidian/plugins/glyphit/';
 * ```
 */
async function resolveExportPath() {
  try {
    const env = await import('./env.js');
    return env.obsidianExportPath ?? null;
  } catch {
    console.log(
      '[iconize] No env.js found - building to ./main.js only. See rollup.config.js to set up copying into a vault.',
    );
    return null;
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

const cmModules = [
  '@codemirror/autocomplete',
  '@codemirror/closebrackets',
  '@codemirror/collab',
  '@codemirror/comment',
  '@codemirror/commands',
  '@codemirror/fold',
  '@codemirror/highlight',
  '@codemirror/gutter',
  '@codemirror/history',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/matchbrackets',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/stream-parser',
  '@codemirror/rangeset',
  '@codemirror/panel',
  '@codemirror/matchbrackets',
  '@codemirror/text',
  '@codemirror/tooltip',
  '@codemirror/view',
];

export default async () => {
  const obsidianExportPath = await resolveExportPath();

  return {
    input: './src/main.ts',
    output: {
      file: './main.js',
      // Inline source maps make debugging a dev build possible, but they more
      // than double what ships to users, so release builds go without.
      sourcemap: isProd ? false : 'inline',
      format: 'cjs',
      exports: 'default',
      banner,
    },
    external: ['obsidian', ...cmModules],
    plugins: [
      alias({
        entries: {
          '@app': 'src',
          '@lib': 'src/lib',
        },
      }),
      typescript({
        // Tests are typechecked by `tsc`/vitest, not by the bundler. Without
        // this they are compiled on every build and report errors for code
        // that never ships.
        exclude: ['**/*.test.ts', 'src/test-utils.ts', '**/test-setup.ts'],
        // Kept in step with the Rollup-level setting above, otherwise Rollup
        // warns that it was asked for maps it is not emitting. `inlineSourceMap`
        // has to be overridden explicitly because tsconfig.json turns it on.
        sourceMap: !isProd,
        inlineSourceMap: false,
        inlineSources: !isProd,
      }),
      nodeResolve({ browser: true }),
      commonjs(),
      copy({
        targets: [
          // A loadable plugin folder, ready to copy into any vault's
          // .obsidian/plugins directory for testing.
          { src: './main.js', dest: LOADABLE_PLUGIN_DIR },
          { src: './manifest.json', dest: LOADABLE_PLUGIN_DIR },
          { src: './src/styles.css', dest: LOADABLE_PLUGIN_DIR },

          // And straight into a vault, when env.js says where.
          ...(obsidianExportPath
            ? [
                { src: './main.js', dest: obsidianExportPath },
                { src: './manifest.json', dest: obsidianExportPath },
                { src: './src/styles.css', dest: obsidianExportPath },
              ]
            : []),
        ],
        hook: 'writeBundle',
      }),
    ],
    onwarn: (warning) => {
      if (warning.code === 'THIS_IS_UNDEFINED') return;

      console.warn(warning.message);
    },
  };
};
